var fs = require('fs');
var path = require('path');

// Replace with your unique name
exports.appName = 'habg-api';

// Use your own Server Key as generated by Google Developer Console
// For more details, see http://developer.android.com/google/gcm/gs.html
exports.gcmServerApiKey = 'AIzaSyA2jrWf0ZX1lf9v0sfZiszzBnJ0HO4QaYM';
